// <auto-generated />
using System;
using Company_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Company_API.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20181124095813_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Company_API.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<DateTime>("LastClickOn");

                    b.Property<string>("Name");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new { CompanyId = 1, Address1 = "Scotland Yard", Address2 = "221B BAKER STREET LONDON", LastClickOn = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "First Company" },
                        new { CompanyId = 2, Address1 = "Walse Yard", Address2 = "221B BAKER Avenue LONDON", LastClickOn = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Second Company" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
